mapping:
  deterministic:
    - false
    - true
graph:
  type: knn
  k:
    - 4
model:
  d:
    - 16
    - 32
  enc_hidden_dim:
    - 64
  dec_hidden_dim:
    - 256
  K:
    - 20
training:
  lr:
    - 0.001
    - 0.005
  epochs:
    - 200
  dropout_decoder:
    - 0.2
loss_weights:
  lambda_rec_spot:
    - 1.0
  lambda_rec_state:
    - 1.0
  lambda_clust:
    - 1.0
  lambda_state_entropy:
    - 1.0
  lambda_spot_entropy:
    - 1.0
