data:
  sc_path: C:\Users\zi69hebi\Dev\10_Alignment\Data\01_Datasets\04_ColorectalCancer\sc.h5ad
  st_paths:
    - C:\Users\zi69hebi\Dev\10_Alignment\Data\01_Datasets\04_ColorectalCancer\patches_4x4\patch_2_2\st_top30hvg.h5ad
    - C:\Users\zi69hebi\Dev\10_Alignment\Data\01_Datasets\04_ColorectalCancer\patches_4x4\patch_2_2\st_top50hvg.h5ad
    - C:\Users\zi69hebi\Dev\10_Alignment\Data\01_Datasets\04_ColorectalCancer\patches_4x4\patch_2_2\st_top100hvg.h5ad
    - C:\Users\zi69hebi\Dev\10_Alignment\Data\01_Datasets\04_ColorectalCancer\patches_4x4\patch_2_2\st_top200hvg.h5ad
    - C:\Users\zi69hebi\Dev\10_Alignment\Data\01_Datasets\04_ColorectalCancer\patches_4x4\patch_2_2\st.h5ad
output:
  result_folder: C:\Users\zi69hebi\Dev\10_Alignment\Data\02_Results\04_ColorectalCancer_4patch22_VaryHVGS
  metric_folder: C:\Users\zi69hebi\Dev\10_Alignment\Data\03_Metrics\04_ColorectalCancer_4patch22_VaryHVGS
mapping:
  deterministic: true
graph:
  type: knn
  k:
    - 4
model:
  d:
    - 16
  enc_hidden_dim:
    - 64
  dec_hidden_dim:
    - 256
  K:
    - 20
training:
  lr:
#    - 0.008
#    - 0.005
#    - 0.01
#    - 0.02
    - 0.05
#    - 0.1
  epochs:
    - 1000
  dropout_decoder:
    - 0.0
  normalize_and_log:
    - false
  use_cm:
    - true
loss_weights:
  - lambda_rec_spot: 1.0
#    lambda_rec_gene: 1.0
    lambda_rec_gene: 0
    lambda_rec_state: 0
    lambda_clust: 0
#    lambda_state_entropy: 0.20
#    lambda_spot_entropy: 0.15
    lambda_state_entropy: 0.01
    lambda_spot_entropy: 0.008
