name: alternative-idea
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.13
  - pip
  - pandas==2.2.3
  - scipy==1.17.0
  - pyyaml==6.0.3
  - anndata==0.12.7
  - pytorch==2.9.1
  - pytorch_geometric==2.7.0
  - matplotlib==3.9.2
  - scanpy==1.11.5
  # dev
  - mypy==1.19.1
  - black==26.1.0
  - pytest==9.0.2
  - pre-commit==4.5.1
